import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)
import cart from "./cart";
import address from "./address";
import order from "./order";
import pay from "./pay";

export default new Vuex.Store({
  state: {
    username:null,//用户名
    active:0,//0123对应底部四个导航栏
    mygoods:[
      {
        id:1,
        name:"小米10 Pro",
        price:"4999",
        brief:"骁龙865 / 50倍变焦",
        test1:"① 骁龙865旗舰平台，双模5G，用久了也不卡",
        test2:"② 向往的生活同款手机，1亿像素8K电影相机",
        test3:"③ 对称式立体声，有声、有势，一听即知",
        // 存储相应商品的轮播图图片，有空再搞了
        swiper:[
          require("../assets/img/swiper/011.jpg"),
          require("../assets/img/swiper/012.jpg"),
          require("../assets/img/swiper/013.jpg"),
        ],
        //imgs:require("../assets/img/description/01.jpg"),
        imgs:require("../assets/img/description/01.jpg"),
      },
      {
        id:2,
        name:"小米10",
        price:"3799",
        brief:"骁龙865/1亿像素相机",
        test1:"① 骁龙865旗舰平台，双模5G，用久了也不卡",
        test2:"② 1亿像素8K电影相机",
        test3:"③ 6.67英寸 AMOLED 双曲面屏幕，刷新屏幕新体验",
        swiper:[
          require("../assets/img/swiper/021.jpg"),
          require("../assets/img/swiper/022.jpg"),
          require("../assets/img/swiper/023.jpg"),
        ],
        imgs:require("../assets/img/description/02.jpg"),
      },
      {
        id:3,
        name:"Redmi Note 8 Pro",
        price:"1599",
        brief:"6400万全场景四摄",
        test1:"① 120Hz双倍流畅体验，信息仿佛在指尖流淌",
        test2:"② 索尼6400万前后六摄，每一拍都惊艳",
        test3:"③ 多功能NFC，3.5mm 耳机孔，你想要的都没少",
        swiper:[
          require("../assets/img/swiper/031.jpg"),
          require("../assets/img/swiper/032.jpg"),
          require("../assets/img/swiper/033.jpg"),
        ],
        imgs:require("../assets/img/description/03.jpg"),
      },
      {
        id:4,
        name:"Redmi K30 5G",
        price:"1999",
        brief:"双模5G，120Hz流速屏",
        test1:"① 双模5G，低功耗5G处理器，为你的手机提供澎湃动力",
        test2:"② 120Hz双倍流畅体验，信息仿佛在指尖流淌",
        test3:"③ 索尼6400万前后六摄，每一拍都惊艳",
        swiper:[
          require("../assets/img/swiper/041.jpg"),
          require("../assets/img/swiper/042.jpg"),
          require("../assets/img/swiper/043.jpg"),
        ],
        imgs:require("../assets/img/description/04.jpg"),
      },
      {
        id:5,
        name:"Redmi Note 8 Pro",
        price:"1299",
        brief:"6400万全场景四摄",
        test1:"① 6400万四摄小金刚，超强解析力，超震撼",
        test2:"② 液冷游戏芯片，王者玩家的配置",
        test3:"③ 4500mAh大电池，游戏9小时，2小时闪速满电",
        swiper:[
          require("../assets/img/swiper/051.jpg"),
          require("../assets/img/swiper/052.jpg"),
          require("../assets/img/swiper/053.jpg"),
        ],
        imgs:require("../assets/img/description/05.jpg"),
      },
      {
        id:6,
        name:"Redmi Note 8",
        price:"899",
        brief:"千元4800万四摄",
        test1:"① 4800万全场景四摄，生活点滴记录，一部就够了",
        test2:"② 美学配色，2.5D玻璃机身，握在手里的盛世美颜",
        test3:"③ 纳米防泼溅镀层，大电池，从容应对日常生活",
        swiper:[
          require("../assets/img/swiper/061.jpg"),
          require("../assets/img/swiper/062.jpg"),
          require("../assets/img/swiper/063.jpg"),
        ],
        imgs:require("../assets/img/description/06.jpg"),
      },
      {
        id:7,
        name:"扫拖一体机器人",
        price:"1499",
        brief:"扫得干净,拖得彻底",
        test1:"① 5层地图记忆，多模式预约请扫",
        test2:"② 3种扫拖模式",
        test3:"③ S型+Y字型拖地",
        swiper:[
          require("../assets/img/swiper/071.jpg"),
          require("../assets/img/swiper/072.jpg"),
          require("../assets/img/swiper/073.jpg"),
        ],
        imgs:require("../assets/img/description/07.jpg"),
      },
      {
        id:8,
        name:"小米智能摄像机",
        price:"179",
        brief:"高清画质,守护家园",
        test1:"① 1080P",
        test2:"② 红外夜视",
        test3:"③ 双向语音",
        swiper:[
          require("../assets/img/swiper/081.jpg"),
          require("../assets/img/swiper/082.jpg"),
          require("../assets/img/swiper/081.jpg"),
        ],
        imgs:require("../assets/img/description/08.jpg"),
      },
      {
        id:9,
        name:"小米AI音箱",
        price:"229",
        brief:"听音乐,语音遥控家电",
        test1:"① 能播音乐 、讲故事、听相声 ",
        test2:"② 能查路况、设闹钟",
        test3:"③ 还能控制智能设备",
        swiper:[
          require("../assets/img/swiper/091.jpg"),
          require("../assets/img/swiper/092.jpg"),
          require("../assets/img/swiper/093.jpg"),
        ],
        imgs:require("../assets/img/description/09.jpg"),
      },
      {
        id:10,
        name:"小米体脂秤2",
        price:"99",
        brief:"轻松掌握身体脂肪率",
        test1:"① G字型传感器",
        test2:"② 高精准BIA芯片",
        test3:"③ 13项身体数据",
        swiper:[
          require("../assets/img/swiper/101.jpg"),
          require("../assets/img/swiper/102.jpg"),
          require("../assets/img/swiper/103.jpg"),
        ],
        imgs:require("../assets/img/description/10.jpg"),
      },
      {
        id:11,
        name:"小米净水器",
        price:"1099",
        brief:"400加仑大流量,RO膜滤除重金属",
        test1:"① 400加仑大通量",
        test2:"② RO膜滤除重金属",
        test3:"③ 上市热销超120W台",
        swiper:[
          require("../assets/img/swiper/111.jpg"),
          require("../assets/img/swiper/112.jpg"),
          require("../assets/img/swiper/113.jpg"),
        ],
        imgs:require("../assets/img/description/11.jpg"),
      },
      {
        id:12,
        name:"小米手环4",
        price:"149",
        brief:"大屏彩显,20天超长续航",
        test1:"① 全新AMOLED大屏彩显，支持77种个性主题",
        test2:"② 拥有20天超长续航，20天看见自己的改变",
        test3:"③ 24小时高精准心率监测，时刻关注你，守护你",
        swiper:[
          require("../assets/img/swiper/121.jpg"),
          require("../assets/img/swiper/122.jpg"),
          require("../assets/img/swiper/123.jpg"),
        ],
        imgs:require("../assets/img/description/12.jpg"),
      },
      {
        id:13,
        name:"全面屏55英寸",
        price:"1599",
        brief:"全面屏设计,人工智能语音",
        test1:"① 全面屏设计 超高屏占比",
        test2:"② 4K HDR 超高清画质",
        test3:"③ AIoT智能互联",
        swiper:[
          require("../assets/img/swiper/131.jpg"),
          require("../assets/img/swiper/132.jpg"),
          require("../assets/img/swiper/133.jpg"),
        ],
        imgs:require("../assets/img/description/13.jpg"),
      },
      {
        id:14,
        name:"电视4A 65",
        price:"2299",
        brief:"4K HDR，人工智能语音系统",
        test1:"① 全面屏设计 超高屏占比",
        test2:"② 4K HDR 超高清画质",
        test3:"③ 内置小爱同学 AI交互",
        swiper:[
          require("../assets/img/swiper/141.jpg"),
          require("../assets/img/swiper/142.jpg"),
          require("../assets/img/swiper/143.jpg"),
        ],
        imgs:require("../assets/img/description/14.jpg"),
      },
      {
        id:15,
        name:"电视4A 32",
        price:"599",
        brief:"人工智能系统,高清液晶屏",
        test1:"① 高清液晶屏 画面更细腻",
        test2:"② 人工智能系统 懂内容也懂你",
        test3:"③ 64位四核处理器	",
        swiper:[
          require("../assets/img/swiper/151.jpg"),
          require("../assets/img/swiper/152.jpg"),
          require("../assets/img/swiper/153.jpg"),
        ],
        imgs:require("../assets/img/description/15.jpg"),
      },
      {
        id:16,
        name:"电视4A 43",
        price:"1099",
        brief:"人工智能系统,FHD全高清屏",
        test1:"① 全高清分辨率 画质清晰细腻",
        test2:"② 智能PatchWall操作系统",
        test3:"③ 64位四核高性能处理器",
        swiper:[
          require("../assets/img/swiper/161.jpg"),
          require("../assets/img/swiper/162.jpg"),
          require("../assets/img/swiper/163.jpg"),
        ],
        imgs:require("../assets/img/description/16.jpg"),
      },
      {
        id:17,
        name:"电视4A 50",
        price:"1499",
        brief:"4K HDR，人工智能语音系统",
        test1:"① 高清液晶屏 画质细腻清晰",
        test2:"② 人工智能系统 想你所想投你所好",
        test3:"③ 64位处理器 性能强劲",
        swiper:[
          require("../assets/img/swiper/171.jpg"),
          require("../assets/img/swiper/172.jpg"),
          require("../assets/img/swiper/173.jpg"),
        ],
        imgs:require("../assets/img/description/16.jpg"),
      },
      {
        id:18,
        name:"全面屏电视E43C",
        price:"1149",
        brief:"时尚全面屏设计,人工智能语音",
        test1:"① 4K HDR 超高清画质 画面栩栩如生",
        test2:"② 人工智能语音系统  更聪明更懂你",
        test3:"③ 64位核处理器 高速运行 行云流水",
        swiper:[
          require("../assets/img/swiper/181.jpg"),
          require("../assets/img/swiper/182.jpg"),
          require("../assets/img/swiper/183.jpg"),
        ],
        imgs:require("../assets/img/description/18.jpg"),
      },
      {
        id:19,
        name:"Air 13.3 2019款",
        price:"4999",
        brief:"独立显卡,指纹解锁",
        test1:"① 全高清屏幕",
        test2:"② 长续航全金属 ",
        test3:"③ 像杂志一样随身携带",
        swiper:[
          require("../assets/img/swiper/191.jpg"),
          require("../assets/img/swiper/192.jpg"),
          require("../assets/img/swiper/193.jpg"),
        ],
        imgs:require("../assets/img/description/19.jpg"),
      },
      {
        id:20,
        name:"RedmiBook 13",
        price:"4199",
        brief:"全面屏包罗万千视界",
        test1:"① 14英寸FHD全面屏",
        test2:"② 超轻薄金属机身",
        test3:"③ AMD锐龙 4500U 处理器",
        swiper:[
          require("../assets/img/swiper/201.jpg"),
          require("../assets/img/swiper/202.jpg"),
          require("../assets/img/swiper/203.jpg"),
        ],
        imgs:require("../assets/img/description/20.jpg"),
      },
      {
        id:21,
        name:"Redmi波轮洗衣机1A",
        price:"749",
        brief:"8kg大容量，一键操作，父母都爱用",
        test1:"① 洗的净、烘得干，全家衣物一台就够了",
        test2:"② 1小时即洗即穿，梅雨天也穿得干干爽爽",
        test3:"③ 一级能效，省水省电",
        swiper:[
          require("../assets/img/swiper/211.jpg"),
          require("../assets/img/swiper/212.jpg"),
          require("../assets/img/swiper/213.jpg"),
        ],
        imgs:require("../assets/img/description/21.jpg"),
      },
      {
        id:22,
        name:"米家洗烘一体机",
        price:"1999",
        brief:"智能烘干，高效净衣，省水省电",
        test1:"① 22分钟快速洗",
        test2:"② 10种模式",
        test3:"③ 桶自洁避免细菌滋生",
        swiper:[
          require("../assets/img/swiper/221.jpg"),
          require("../assets/img/swiper/222.jpg"),
          require("../assets/img/swiper/223.jpg"),
        ],
        imgs:require("../assets/img/description/22.jpg"),
      },
      {
        id:23,
        name:"Redmi波轮洗衣机1S",
        price:"779",
        brief:"小身材大容量，聪明洗衣，可预约",
        test1:"① 洗的净、烘得干，全家衣物一台就够了",
        test2:"② 1小时即洗即穿，梅雨天也穿得干干爽爽",
        test3:"③ 一级能效，省水省电",
        swiper:[
          require("../assets/img/swiper/231.jpg"),
          require("../assets/img/swiper/232.jpg"),
          require("../assets/img/swiper/233.jpg"),
        ],
        imgs:require("../assets/img/description/23.jpg"),
      },
      {
        id:24,
        name:"变频滚筒洗衣机1A 8kg",
        price:"1199",
        brief:"8kg大容量，超薄机身，高效净衣",
        test1:"① 洗的净、烘得干，全家衣物一台就够了",
        test2:"② 1小时即洗即穿，梅雨天也穿得干干爽爽",
        test3:"③ 一级能效，省水省电",
        swiper:[
          require("../assets/img/swiper/241.jpg"),
          require("../assets/img/swiper/242.jpg"),
          require("../assets/img/swiper/243.jpg"),
        ],
        imgs:require("../assets/img/description/24.jpg"),
      },
      {
        id:25,
        name:"变频滚筒洗衣机1S 8kg",
        price:"1299",
        brief:"超薄机身大容量，除菌净衣更健康",
        test1:"① 洗的净、烘得干，全家衣物一台就够了",
        test2:"② 1小时即洗即穿，梅雨天也穿得干干爽爽",
        test3:"③ 一级能效，省水省电",
        swiper:[
          require("../assets/img/swiper/251.jpg"),
          require("../assets/img/swiper/252.jpg"),
          require("../assets/img/swiper/253.jpg"),
        ],
        imgs:require("../assets/img/description/25.jpg"),
      },
      {
        id:26,
        name:"变频滚筒洗衣机1C 10kg",
        price:"1499",
        brief:"10kg大容量,专业羽绒洗,省水省电",
        test1:"① 洗的净、烘得干，全家衣物一台就够了",
        test2:"② 1小时即洗即穿，梅雨天也穿得干干爽爽",
        test3:"③ 一级能效，省水省电",
        swiper:[
          require("../assets/img/swiper/261.jpg"),
          require("../assets/img/swiper/262.jpg"),
          require("../assets/img/swiper/263.jpg"),
        ],
        imgs:require("../assets/img/description/26.jpg"),
      },
      {
        id:27,
        name:"米家驱蚊器 智能版",
        price:"59",
        brief:"智能操控,一键循环定时",
        test1:"① 智能操控",
        test2:"② 一键循环定时",
        test3:"③ 长效驱蚊",
        swiper:[
          require("../assets/img/swiper/271.jpg"),
          require("../assets/img/swiper/272.jpg"),
          require("../assets/img/swiper/273.jpg"),
        ],
        imgs:require("../assets/img/description/27.jpg"),
      },
      {
        id:28,
        name:"米家直流变频落地扇1X",
        price:"299",
        brief:"100挡细腻调速，老人小孩都能用",
        test1:"① 「纳凉特辑风扇周，7.13-7.16享冰点价279元！」",
        test2:"② 26.6dB(A)超静音",
        test3:"③ 100挡细腻调速，老人小孩都能用",
        swiper:[
          require("../assets/img/swiper/281.jpg"),
          require("../assets/img/swiper/282.jpg"),
          require("../assets/img/swiper/283.jpg"),
        ],
        imgs:require("../assets/img/description/28.jpg"),
      },
      {
        id:29,
        name:"Redmi 8 4GB+64GB",
        price:"799",
        brief:"4800万全场景四摄，生活点滴记录",
        test1:"① 4800万全场景四摄，生活点滴记录，一部就够了",
        test2:"② 美学配色，2.5D玻璃机身，握在手里的盛世美颜",
        test3:"③ 纳米防泼溅镀层，大电池，从容应对日常生活",
        swiper:[
          require("../assets/img/swiper/291.jpg"),
          require("../assets/img/swiper/292.jpg"),
          require("../assets/img/swiper/293.jpg"),
        ],
        imgs:require("../assets/img/description/29.jpg"),
      },
      {
        id:30,
        name:"Redmi Note 8 6GB+64GB",
        price:"1099",
        brief:"6400万旗舰级全场景四摄",
        test1:"① 6400万旗舰级全场景四摄",
        test2:"② 液冷游戏芯",
        test3:"③ 4500mAh大电量",
        swiper:[
          require("../assets/img/swiper/301.jpg"),
          require("../assets/img/swiper/302.jpg"),
          require("../assets/img/swiper/303.jpg"),
        ],
        imgs:require("../assets/img/description/30.jpg"),
      },
      {
        id:31,
        name:"90分框体旅行箱 24英寸",
        price:"599",
        brief:"箱体100%铝镁合金,坚固轻盈",
        test1:"① 箱体100%铝镁合金",
        test2:"② 坚固轻盈",
        test3:"③ 万向静音轮 ",
        swiper:[
          require("../assets/img/swiper/311.jpg"),
          require("../assets/img/swiper/312.jpg"),
          require("../assets/img/swiper/313.jpg"),
        ],
        imgs:require("../assets/img/description/31.jpg"),
      },
      {
        id:32,
        name:"Redmi 7A 3GB+32GB",
        price:"599",
        brief:"4000mAh大电量，持久长续航",
        test1:"① 4000mAh大电量，持久长续航",
        test2:"② 巨无霸字体，大字阅读更轻松",
        test3:"③ 整机生活防泼溅，手机自带隐形“雨衣”",
        swiper:[
          require("../assets/img/swiper/321.jpg"),
          require("../assets/img/swiper/322.jpg"),
          require("../assets/img/swiper/323.jpg"),
        ],
        imgs:require("../assets/img/description/32.jpg"),
      },
    ]
  },
  mutations: {
  },
  actions: {
  },
  modules: {
    cart,   //购物车 详情页与购物车
    address, //我的地址
    order, //订单数据
    pay    //支付界面
  }
})
